server.port=9090
spring.application.name=order-manager

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

# JWT
jwt.secret=b2chat-order-manager-super-secret-key-123
jwt.expiration-ms=3600000

custom.db.hostUrl =localhost:5432/b2chat_manager
custom.db.username = postgres
custom.db.password = Sofka2025*
custom.db.schema = public

# RabbitMQ - conexión
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ - exchange
rabbitmq.order.exchange=order.exchange

# RabbitMQ - colas
rabbitmq.order.process-queue=order.process.queue
rabbitmq.order.processing-queue=order.processing.queue
rabbitmq.order.received-queue=order.notification.received.queue
rabbitmq.order.completed-queue=order.notification.completed.queue
rabbitmq.order.cancelled-queue=order.notification.cancelled.queue

# RabbitMQ - routing keys
rabbitmq.order.process-key=order.process
rabbitmq.order.processing-key=order.processing
rabbitmq.order.received-key=order.notification.received
rabbitmq.order.completed-key=order.notification.completed
rabbitmq.order.cancelled-key=order.notification.cancelled

# Email (Gmail SMTP — reemplaza con tus credenciales)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xxxxx@gmail.com
spring.mail.password=xxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true